1097 super admin je peux affecter une structure référente a une structure
betagouv/eva-serveur pull request #1039
Opened 2022-02-09 17:11 UTC by cprodhomme

J'ai fait en sorte que l'on ne puisse pas s'inscrire à une structure qui a des dépendances 

![Capture d’écran 2022-02-09 à 18 10 08](https://user-images.githubusercontent.com/7428736/153252971-0f78b56e-532e-4442-8c63-4dbc165dc03a.png)
![Capture d’écran 2022-02-09 à 18 10 12](https://user-images.githubusercontent.com/7428736/153252977-c5ec9cbd-5a98-4dc4-b3de-50cb16eb655f.png)

2022-02-09 17:11 UTC, cprodhomme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Super admin, je peux affecter une structure référente à une structure](https://trello.com/c/xMi6984V/1097-super-admin-je-peux-affecter-une-structure-r%C3%A9f%C3%A9rente-%C3%A0-une-structure)

2022-02-11 09:25 UTC, etienneCharignon commented
J'identifie un problème, qui est peut-être pas très grave, c'est qu'on ne peut pas avoir de "super-structure" qui n'aurait pas de structures dépendantes. C'est une situation qui arrive au moment de la création. En général, on la créé puis on lui ajoute des sous-structures, mais ça peut parfois prendre du temps et du coup, pendant ce temps là la super-structure est vue comme une sous-structure.

2022-02-11 09:27 UTC, etienneCharignon commented
> J'identifie un problème, qui est peut-être pas très grave, c'est qu'on ne peut pas avoir de "super-structure" qui n'aurait pas de structures dépendantes. C'est une situation qui arrive au moment de la création. En général, on la créé puis on lui ajoute des sous-structures, mais ça peut parfois prendre du temps et du coup, pendant ce temps là la super-structure est vue comme une sous-structure.

J'ai l'impression que j'aimerai mieux avoir un attribut `type` plutôt que de retrouve le type en fonction de la présence ou nom de sous-structure.

2022-02-14 16:49 UTC, etienneCharignon commented on app/observers/compte_observer.rb
> +    return unless compte.structure&.type == 'StructureLocale'
On pourrait peut-être utiliser le nom de la class plutôt qu'une chaine de caractère ?

2022-02-14 16:50 UTC, etienneCharignon commented on app/views/admin/dashboard/_modal_validation_comptes_en_attente.html.erb
> +            lien = if structure.type == 'StructureAdministrative'
ici aussi, le nom de la class ?

2022-02-14 16:51 UTC, etienneCharignon commented on app/views/admin/dashboard/_modal_validation_comptes_en_attente.html.erb
> +            lien = if structure.type == 'StructureAdministrative'
J'aurai bien inversé le test pour maximiser le nombre de test identique et comparer avec "StructureLocale"

2022-02-14 16:53 UTC, etienneCharignon commented on app/views/compte_mailer/alerte_admin.html.erb
> +<% lien = if structure.type == 'StructureAdministrative'
La aussi retourner le if et comparer au nom de la class si possible

2022-02-14 17:35 UTC, etienneCharignon requested changes
Plusieurs commentaires sur la position des attributs des structures dans la hierachi des types

2022-02-14 17:35 UTC, etienneCharignon commented on app/models/structure.rb
> +  has_many :structures_dependantes, class_name: 'Structure', foreign_key: :structure_referente_id
structures_dependantes est un attribut de StructureAdministrative seulement

2022-02-14 17:35 UTC, etienneCharignon commented on app/models/structure.rb
>    auto_strip_attributes :code_postal, delete_whitespaces: true
code_postal est un attribut de StructureLocale seulement
Attention car cette propriété est impliqué dans le nom d'affichage dans `display_name()`

2022-02-14 17:35 UTC, etienneCharignon commented on app/models/structure.rb
> +  belongs_to :structure_referente, optional: true, class_name: 'Structure'
structures_referente est un attribut de StructureLocale seulement

2022-02-14 17:35 UTC, etienneCharignon commented on app/models/structure.rb
>    TYPE_NON_COMMUNIQUE = 'non_communique'
TYPE_NON_COMMUNIQUE est une constante de StructureLocale

2022-02-14 17:35 UTC, etienneCharignon commented on app/models/structure.rb
>  class Structure < ApplicationRecord
Je ne comprend pas où es passé `type_structure`

2022-02-15 09:05 UTC, cprodhomme commented on app/models/structure.rb
> +  belongs_to :structure_referente, optional: true, class_name: 'Structure'
C'est pas forcement vrai car si on veut faire une structure Administrative "Paris" et aussi une structure administrative "Iles-de-France", alors j'aimerais qu'elles soient liées

2022-02-15 09:05 UTC, cprodhomme commented on app/models/structure.rb
>  class Structure < ApplicationRecord
dans StructureLocale

2022-02-16 11:01 UTC, etienneCharignon commented
Sur la page d'une structure administrative, on voit un champ "Type de structure" alors que les structures administrative n'en ont pas. Si ? En plus ça affiche un hash avec tout les types
<img width="785" alt="Capture d’écran 2022-02-16 à 11 55 02" src="https://user-images.githubusercontent.com/298214/154250551-f99d9bf1-99f3-4b72-8ca8-2065c47fc13a.png">

Et quand on veut modifier une structure administrative on demande le code postal et le type
<img width="683" alt="Capture d’écran 2022-02-16 à 12 00 10" src="https://user-images.githubusercontent.com/298214/154251191-2cae9ebb-0377-4171-a171-f73f24f7a3dc.png">

2022-02-16 11:09 UTC, etienneCharignon commented
On ne peut plus afficher la page des comptes
http://localhost:3000/pro/admin/comptes

2022-02-16 17:40 UTC, etienneCharignon commented on spec/integrations/compte_spec.rb
> +    context "quand le compte fait partie d'une structure terrain" do
J'aurais bien ajouté un test pour vérifier qu'on ne relance pas les comptes créé pour les structures administratives

2022-02-16 17:42 UTC, etienneCharignon commented on spec/models/structure_spec.rb
> +  describe '#display_name' do
Ce test est devrait être dans structure_local_spec

2022-02-16 20:14 UTC, etienneCharignon commented
😢 il y a encore un problème… les structures administratives apparaissent dans la liste des structures locales
<img width="1157" alt="Capture d’écran 2022-02-16 à 21 12 53" src="https://user-images.githubusercontent.com/298214/154349348-0caa0901-ae68-4c12-a95b-cc3901bcb1fd.png">

2022-02-17 09:12 UTC, cprodhomme commented
> 😢 il y a encore un problème… les structures administratives apparaissent dans la liste des structures locales <img alt="Capture d’écran 2022-02-16 à 21 12 53" width="1157" src="https://user-images.githubusercontent.com/298214/154349348-0caa0901-ae68-4c12-a95b-cc3901bcb1fd.png">

Je n'ai pas le cas en local
Ca me parait impossible, est-ce que tu es sûr de tes données ?

2022-02-18 09:51 UTC, etienneCharignon commented
> 
> Je n'ai pas le cas en local Ca me parait impossible, est-ce que tu es sûr de tes données ?


Ouf, en effet, c'était mes données, a cause des différents tests que j'ai fait au cours de la réalisation. J'avais en fait deux structures, une local et une administrative avec le même nom… d'où la méprise. Du coup, c'est bon pour moi.

2022-02-18 09:54 UTC, etienneCharignon commented
On peut ajouter une structure local en structure référente. ça pause problème car les structures local ne sont pas sensées avoir de fille.
<img width="1168" alt="Capture d’écran 2022-02-18 à 10 53 28" src="https://user-images.githubusercontent.com/298214/154659629-af1e222f-e43d-449b-9785-4119103397a4.png">

2022-02-18 10:23 UTC, merged

2022-02-18 10:27 UTC, cprodhomme commented
🎉