🗃️ Ajoute un index d'unicité sur les données sociodémographique
betagouv/eva-serveur pull request #1394
Opened 2023-01-04 10:34 UTC by cprodhomme

2023-01-04 10:34 UTC, cprodhomme commented
![](https://github.trello.services/images/mini-trello-icon.png) [🐛 plusieurs données sociodémographiques ont été enregistrées pour une même évaluation.](https://trello.com/c/TMoQp8Jl/1579-%F0%9F%90%9B-plusieurs-donn%C3%A9es-sociod%C3%A9mographiques-ont-%C3%A9t%C3%A9-enregistr%C3%A9es-pour-une-m%C3%AAme-%C3%A9valuation)

2023-01-06 17:37 UTC, etienneCharignon commented
@cprodhomme je propose d'ajouter une transaction à l'update d'une évaluation (voir commit). Pour le reste de la PR c'est ok pour moi. Je veux bien ta confirmation pour cette transaction.

2023-01-09 15:07 UTC, etienneCharignon commented on db/migrate/20230104103244_ajoute_index_unicite_pour_donnees_socio_demographique.rb
> +    add_index :donnees_sociodemographiques, :evaluation_id, unique: true
De ce que je constate, l'ajout de cette index unique empêche la mise à jour des données sociodémographiques lors d'un second appel PATH sur l'API.

2023-01-09 15:09 UTC, etienneCharignon requested changes
De ce que je constate, l'ajout de cette index unique empêche la mise à jour des données sociodémographiques lors d'un second appel PATH sur l'API.

2023-01-09 17:03 UTC, etienneCharignon approved these changes

2023-01-09 17:22 UTC, merged