affiche le temps de passation pour une évaluation
betagouv/eva-serveur pull request #607
Opened 2020-12-14 16:13 UTC by shanser

pour https://trello.com/c/XlP12oEw/334-conseiller-je-peux-conna%C3%AEtre-le-temps-de-passation-dune-%C3%A9valuation

2020-12-18 10:42 UTC, shanser commented
finalement j'ai regroupé avec le tableau du début de la page et retiré la sidebar

![Capture d’écran 2020-12-18 à 11 41 46](https://user-images.githubusercontent.com/28393/102605759-1150c200-4126-11eb-9827-8928e4b65976.png)

2020-12-21 15:04 UTC, etienneCharignon commented on app/models/statistiques_evaluation.rb
> +    @debut = premier_evenement.date
J'ai du corrigé le code pour qu'il passe les tests… mais CircleCi ne rapportait pas l'erreur ! 
Enfin bref, maintenant ça passe…

Par contre, tu faisais un `return if @debut.blank?` mais je ne vois pas pourquoi faire ça. Est-ce que tu peux m'en dire plus ?

2020-12-21 16:16 UTC, etienneCharignon commented
Attention, @Alexis-Akinyemi nous indique dans le ticket https://trello.com/c/gUZYm1iE que ce n'est pas une bonne chose d'afficher le temps de passation dans la restitution.

2020-12-21 16:17 UTC, etienneCharignon requested changes
Attention, @Alexis-Akinyemi nous indique dans le ticket https://trello.com/c/gUZYm1iE que ce n'est pas une bonne chose d'afficher le temps de passation dans la restitution.

2020-12-28 14:21 UTC, shanser commented on app/models/statistiques_evaluation.rb
> +    @debut = premier_evenement.date
effectivement, ça ne passait pas :(

Pour la même raison que tu fais `return if premier_evenement.nil?`
J'ai tendance à utiliser `.blank?` parce que ça gère aussi le cas où une collection est vide, mais dans ce cas c'est équivalent

2020-12-28 14:31 UTC, shanser commented
Le temps de passation n'est visible que pour les admins.

Vue admin:
<img width="1405" alt="Capture d’écran 2020-12-28 à 15 30 08" src="https://user-images.githubusercontent.com/28393/103220934-bb4bfd80-4921-11eb-857f-fa5251acf739.png">

Vue conseiller:
<img width="1404" alt="Capture d’écran 2020-12-28 à 15 30 47" src="https://user-images.githubusercontent.com/28393/103220948-c30ba200-4921-11eb-8c87-24038903f0b8.png">

2020-12-28 14:33 UTC, merged