WIP - Page aide - Menu
betagouv/eva-serveur pull request #626
Opened 2021-01-04 15:33 UTC by mdomine

Pour : https://trello.com/c/RCxGV3AV/317-conseiller-je-peux-naviguer-facilement-dans-la-section-aide

2021-01-05 13:21 UTC, etienneCharignon requested changes
Cool le sticky, ça marche trop bien !
En terme dynamique en largeur, benjamin voudrait que le menu soit collé à droite, en prenant la même largeur que la gélule blanche de login. La largeur de la section d'aide est fixe aussi et ce sont les espaces à gauche et à droite de celle ci qui sont élastiques.

Je regarde cet après midi pour faire les choses de cette manière en continuant à partir de ce que tu as commencé.

2021-01-05 16:59 UTC, etienneCharignon approved these changes

2021-01-05 17:57 UTC, mdomine commented
C'est cool :) 
Par contre, quand je suis sur un écran plus large je ne vais jusqu'au bout de la navigation. 
La foire aux questions n'est jamais active.

https://www.loom.com/share/e3de616c3da24d20a8f70b850db2aa4e

2021-01-05 19:24 UTC, etienneCharignon commented
> Par contre, quand je suis sur un écran plus large je ne vais jusqu'au bout de la navigation.
> La foire aux questions n'est jamais active.

Et oui mais là j'avoue que j'ai déjà tout donner pour arriver à ce résultat.

2021-01-10 17:53 UTC, etienneCharignon commented on app/views/admin/aide/_menu.html.arb
> +        end
Il me semble que cette liste devrait être construite en partie à partir des catégories présentes dans le modèle de sources d'aides comme dans `app/views/admin/aide/_aide.html.arb`

2021-01-10 17:56 UTC, etienneCharignon commented on config/locales/views/aide.yml
> +        presenter_eva: Présenter l'outil
Ces trois traductions sont en double avec les lignes 25, 26 et 27. On a des exemples dans d'autre fichiers de trad sur la manière de factoriser ça.

2021-01-12 08:30 UTC, etienneCharignon commented on app/views/admin/aide/_menu.html.arb
> +        end
J'ai fais une correction

2021-01-12 09:06 UTC, mdomine commented on app/views/admin/aide/_menu.html.arb
> +        end
C'est ok pour moi :)

2021-01-12 09:34 UTC, etienneCharignon commented on config/locales/views/aide.yml
> +        presenter_eva: Présenter l'outil
J'ai factorisé avec le modèle 😅

2021-01-12 09:38 UTC, etienneCharignon commented on config/locales/views/aide.yml
> +        presenter_eva: Présenter l'outil
@shanser je ne sais pas si j'ai fais les choses "à la rails". Je veux bien que tu y jette un œil.

2021-01-15 12:04 UTC, shanser commented on config/locales/views/aide.yml
> +        presenter_eva: Présenter l'outil
j'ai pas vraiment de meilleure idée

2021-01-15 12:04 UTC, merged